### ISSUE TITLE
Null reference

### ISSUE THREAD

**Issue by BabyGravy** [arramus/Snufkin-Weapons-Xpansion-A19-Stable-Test2020Nov10#1] opened 2020-11-11 12:51 UTC
Getting a Null reference error for the mod's weapons so far it was railgun and zeus weapons from the workbench and inventory crafting area when i look them up

**Comment by arramus** [comment] 2020-11-11 16:42
Hello BabyGravy,

Here are the results of a test on a dedicated server for the Railgun.

Accessing the Railgun and selecting it in creative mode was successful.
![20201112012721_1](https://user-images.githubusercontent.com/71211641/98837708-9e995a80-2486-11eb-9813-a591712af9d2.jpg)

Looking up and selecting the Railgun in the workbench was successful.
![20201112012737_1](https://user-images.githubusercontent.com/71211641/98838013-0485e200-2487-11eb-9ae8-01c6d09c11d2.jpg)

Initiating a request to craft the Railgun was successful.
![20201112012916_1](https://user-images.githubusercontent.com/71211641/98838102-28492800-2487-11eb-8f05-9dd1c17a5b9d.jpg)

The Null Reference Error can be caused by numerous issues. It can be caused by trying to create a weapon that is configured for progression in items.xml but lacks the progression.xml file entry. This is not the case for the Railgun. It can also be caused by incorporating this weapon mod into an overhaul mod that changes multiple default settings. It can also be caused by conflicts whereby another asset is using the same slot that the Railgun uses.

Can you share your game environment setup with regard to mods and customisation? It will help us go through a process of elimination to find the cause.

**Comment by BabyGravy** [comment] 2020-11-12 01:17
I forgot to mention it is a Darkness Falls Server so I took out the
recipe files, so the guns can be found in the world just cant make them.
Sorry should have told ya that it was darkness falls

**Comment by arramus** [comment] 2020-11-12 03:39
One of the testers is actually running the weapons on a Darkness Falls server and had to make some edits to lootcontainer code to integrate into Darkness Falls modifications. You are always welcome to post on the main forum and tag @Dre in your post.

https://community.7daystodie.com/topic/22438-snufkin-weapons-xpansion-a19-stable/

You will also see the mod was update to the latest build which adds crafting for all of the Xpansion weapons and introduces the oakraven X11. I shall close this issue from now BabyGravy but it will always remain visible to others and acts as a good care consideration when bringing this mod to overhauls or mixing other mods into the mix which may create a conflict.

**Closed by arramus** 2020-11-12 03:39 UTC
